name=str(input("enter your name"))
Address=str(input("enter your Address"))
city=str(input("enter your city"))
state=str(input("enter your state"))
zips=str(input("enter your zip"))
phone=int(input("enter your phone number"))
college=str(input("enter your college major"))
print("Your name is ",name)
print("From", Address, "in city ",city,"and the ",state,"and zip code is: ",zips)
print("Your contact number ",phone)
print("Your college major is ",college)
